import type { MigrationInterface, QueryRunner } from "typeorm";
// Immutable migration snapshot. New catalog entries belong in a new migration.
const PERMISSION_CATALOG = [
  {
    code: "dashboard.view",
    domain: "OVERVIEW",
    resource: "dashboard",
    action: "view",
    labelAr: "عرض لوحة المؤشرات",
    descriptionAr: "عرض مؤشرات الإدارة العامة.",
    sensitivity: "NORMAL",
  },
  {
    code: "legislation.view",
    domain: "CONTENT",
    resource: "legislation",
    action: "view",
    labelAr: "عرض التشريعات الإدارية",
    descriptionAr: "عرض المسودات والتشريعات داخل لوحة الإدارة.",
    sensitivity: "NORMAL",
  },
  {
    code: "legislation.create",
    domain: "CONTENT",
    resource: "legislation",
    action: "create",
    labelAr: "إنشاء تشريع",
    descriptionAr: "إنشاء مسودة تشريع جديدة.",
    sensitivity: "NORMAL",
  },
  {
    code: "legislation.update",
    domain: "CONTENT",
    resource: "legislation",
    action: "update",
    labelAr: "تعديل بيانات التشريع",
    descriptionAr: "تعديل البيانات الوصفية والديباجة.",
    sensitivity: "NORMAL",
  },
  {
    code: "legislation.update_published_metadata",
    domain: "CONTENT",
    resource: "legislation",
    action: "update_published_metadata",
    labelAr: "تصحيح بيانات تشريع منشور",
    descriptionAr: "تصحيح البيانات الوصفية دون تغيير النص المنشور.",
    sensitivity: "ELEVATED",
  },
  {
    code: "legislation.submit",
    domain: "CONTENT",
    resource: "legislation",
    action: "submit",
    labelAr: "إرسال التشريع للمراجعة",
    descriptionAr: "نقل المسودة إلى المراجعة.",
    sensitivity: "NORMAL",
  },
  {
    code: "legislation.approve",
    domain: "CONTENT",
    resource: "legislation",
    action: "approve",
    labelAr: "اعتماد التشريع",
    descriptionAr: "اعتماد التشريع ليصبح جاهزًا للنشر.",
    sensitivity: "ELEVATED",
  },
  {
    code: "legislation.publish",
    domain: "CONTENT",
    resource: "legislation",
    action: "publish",
    labelAr: "نشر التشريع",
    descriptionAr: "نشر النسخة المعتمدة للعامة.",
    sensitivity: "CRITICAL",
  },
  {
    code: "legislation.archive",
    domain: "CONTENT",
    resource: "legislation",
    action: "archive",
    labelAr: "أرشفة التشريع",
    descriptionAr: "نقل التشريع المنشور إلى الأرشيف.",
    sensitivity: "ELEVATED",
  },
  {
    code: "article.update",
    domain: "CONTENT",
    resource: "article",
    action: "update",
    labelAr: "تعديل المواد",
    descriptionAr: "تعديل نص المادة وبياناتها.",
    sensitivity: "NORMAL",
  },
  {
    code: "structure.manage",
    domain: "CONTENT",
    resource: "structure",
    action: "manage",
    labelAr: "إدارة بنية التشريع",
    descriptionAr: "إنشاء وتعديل الأبواب والفصول والأقسام.",
    sensitivity: "NORMAL",
  },
  {
    code: "annex.manage",
    domain: "CONTENT",
    resource: "annex",
    action: "manage",
    labelAr: "إدارة الملاحق والجداول",
    descriptionAr: "إنشاء وتعديل اللوائح والملاحق والجداول.",
    sensitivity: "NORMAL",
  },
  {
    code: "relation.manage",
    domain: "CONTENT",
    resource: "relation",
    action: "manage",
    labelAr: "إدارة العلاقات القانونية",
    descriptionAr: "إنشاء وتدقيق علاقات التشريعات.",
    sensitivity: "NORMAL",
  },
  {
    code: "reference.view",
    domain: "CONTENT",
    resource: "reference",
    action: "view",
    labelAr: "عرض القوائم المرجعية",
    descriptionAr: "عرض الأنواع والجهات والموضوعات.",
    sensitivity: "NORMAL",
  },
  {
    code: "reference.manage",
    domain: "CONTENT",
    resource: "reference",
    action: "manage",
    labelAr: "إدارة القوائم المرجعية",
    descriptionAr: "إنشاء وتعديل الأنواع والجهات والموضوعات.",
    sensitivity: "ELEVATED",
  },
  {
    code: "source.view",
    domain: "SOURCES",
    resource: "source",
    action: "view",
    labelAr: "عرض المصادر",
    descriptionAr: "عرض ملفات المصدر ونتائج الاستخراج.",
    sensitivity: "NORMAL",
  },
  {
    code: "source.upload",
    domain: "SOURCES",
    resource: "source",
    action: "upload",
    labelAr: "رفع مصدر",
    descriptionAr: "رفع ملف مصدر جديد.",
    sensitivity: "NORMAL",
  },
  {
    code: "source.review",
    domain: "SOURCES",
    resource: "source",
    action: "review",
    labelAr: "مراجعة المصدر",
    descriptionAr: "اعتماد النص المستخرج بعد مقارنته بالمصدر.",
    sensitivity: "ELEVATED",
  },
  {
    code: "source.create_draft",
    domain: "SOURCES",
    resource: "source",
    action: "create_draft",
    labelAr: "إنشاء مسودة من مصدر",
    descriptionAr: "تحويل المصدر المستخرج إلى مسودة تشريع.",
    sensitivity: "NORMAL",
  },
  {
    code: "source.update",
    domain: "SOURCES",
    resource: "source",
    action: "update",
    labelAr: "تعديل بيانات المصدر",
    descriptionAr: "تصحيح بيانات المصدر وحالة الاستخراج.",
    sensitivity: "NORMAL",
  },
  {
    code: "amendment.view",
    domain: "AMENDMENTS",
    resource: "amendment",
    action: "view",
    labelAr: "عرض التعديلات",
    descriptionAr: "عرض مسودات وعمليات التعديل.",
    sensitivity: "NORMAL",
  },
  {
    code: "amendment.create",
    domain: "AMENDMENTS",
    resource: "amendment",
    action: "create",
    labelAr: "إنشاء تعديل",
    descriptionAr: "إنشاء مسودة عملية تعديل.",
    sensitivity: "NORMAL",
  },
  {
    code: "amendment.review",
    domain: "AMENDMENTS",
    resource: "amendment",
    action: "review",
    labelAr: "مراجعة تعديل",
    descriptionAr: "اعتماد المراجعة القانونية للتعديل.",
    sensitivity: "ELEVATED",
  },
  {
    code: "amendment.publish",
    domain: "AMENDMENTS",
    resource: "amendment",
    action: "publish",
    labelAr: "نشر تعديل",
    descriptionAr: "تطبيق التعديل وإنشاء نسخة زمنية.",
    sensitivity: "CRITICAL",
  },
  {
    code: "quality.view",
    domain: "GOVERNANCE",
    resource: "quality",
    action: "view",
    labelAr: "عرض مشكلات الجودة",
    descriptionAr: "عرض نتائج فحوص الجودة.",
    sensitivity: "NORMAL",
  },
  {
    code: "quality.manage",
    domain: "GOVERNANCE",
    resource: "quality",
    action: "manage",
    labelAr: "معالجة مشكلات الجودة",
    descriptionAr: "حل مشكلة جودة أو تجاهلها.",
    sensitivity: "NORMAL",
  },
  {
    code: "report.view",
    domain: "GOVERNANCE",
    resource: "report",
    action: "view",
    labelAr: "عرض البلاغات",
    descriptionAr: "عرض بلاغات المحتوى.",
    sensitivity: "NORMAL",
  },
  {
    code: "report.manage",
    domain: "GOVERNANCE",
    resource: "report",
    action: "manage",
    labelAr: "معالجة البلاغات",
    descriptionAr: "فرز البلاغات وحلها أو رفضها.",
    sensitivity: "NORMAL",
  },
  {
    code: "audit.view",
    domain: "GOVERNANCE",
    resource: "audit",
    action: "view",
    labelAr: "عرض سجل التدقيق",
    descriptionAr: "عرض العمليات الحساسة وتفاصيل تغيرها.",
    sensitivity: "ELEVATED",
  },
  {
    code: "search.synonym.view",
    domain: "SEARCH",
    resource: "synonym",
    action: "view",
    labelAr: "عرض قاموس البحث",
    descriptionAr: "عرض نسخ المرادفات القانونية.",
    sensitivity: "NORMAL",
  },
  {
    code: "search.synonym.manage",
    domain: "SEARCH",
    resource: "synonym",
    action: "manage",
    labelAr: "إدارة قاموس البحث",
    descriptionAr: "إنشاء مرادفات ونشر نسخ القاموس.",
    sensitivity: "NORMAL",
  },
  {
    code: "search.reindex",
    domain: "SEARCH",
    resource: "index",
    action: "reindex",
    labelAr: "إعادة بناء فهرس البحث",
    descriptionAr: "إطلاق إعادة فهرسة كاملة.",
    sensitivity: "ELEVATED",
  },
  {
    code: "settings.view",
    domain: "SETTINGS",
    resource: "settings",
    action: "view",
    labelAr: "عرض إعدادات المنصة",
    descriptionAr: "عرض الإعدادات والصفحات والتنقل.",
    sensitivity: "NORMAL",
  },
  {
    code: "settings.general.update",
    domain: "SETTINGS",
    resource: "settings",
    action: "general_update",
    labelAr: "تعديل الإعدادات العامة",
    descriptionAr: "تعديل اسم وهوية المنصة.",
    sensitivity: "ELEVATED",
  },
  {
    code: "settings.appearance.update",
    domain: "SETTINGS",
    resource: "settings",
    action: "appearance_update",
    labelAr: "تعديل الهوية والمظهر",
    descriptionAr: "تعديل الألوان والخلفيات والطباعة.",
    sensitivity: "ELEVATED",
  },
  {
    code: "settings.navigation.update",
    domain: "SETTINGS",
    resource: "navigation",
    action: "update",
    labelAr: "إدارة روابط التنقل",
    descriptionAr: "إنشاء وتعديل روابط الترويسة والتذييل.",
    sensitivity: "ELEVATED",
  },
  {
    code: "settings.content.update",
    domain: "SETTINGS",
    resource: "public_page",
    action: "update",
    labelAr: "إدارة الصفحات العامة",
    descriptionAr: "تحرير ونشر الصفحات العامة.",
    sensitivity: "NORMAL",
  },
  {
    code: "settings.workflow.manage",
    domain: "SETTINGS",
    resource: "workflow_policy",
    action: "manage",
    labelAr: "إدارة سياسات سير العمل",
    descriptionAr: "تعطيل سياسات الفصل ومنح استثناءاتها.",
    sensitivity: "CRITICAL",
  },
  {
    code: "user.view",
    domain: "ACCESS",
    resource: "user",
    action: "view",
    labelAr: "عرض المستخدمين",
    descriptionAr: "عرض الحسابات وحالتها.",
    sensitivity: "NORMAL",
  },
  {
    code: "user.create",
    domain: "ACCESS",
    resource: "user",
    action: "create",
    labelAr: "إنشاء مستخدم",
    descriptionAr: "إنشاء حساب إداري جديد.",
    sensitivity: "ELEVATED",
  },
  {
    code: "user.update",
    domain: "ACCESS",
    resource: "user",
    action: "update",
    labelAr: "تعديل المستخدم",
    descriptionAr: "تعديل بيانات الحساب الأساسية.",
    sensitivity: "NORMAL",
  },
  {
    code: "user.disable",
    domain: "ACCESS",
    resource: "user",
    action: "disable",
    labelAr: "تعطيل وتفعيل المستخدم",
    descriptionAr: "تغيير حالة الحساب وإبطال جلساته.",
    sensitivity: "ELEVATED",
  },
  {
    code: "user.reset_password",
    domain: "ACCESS",
    resource: "user",
    action: "reset_password",
    labelAr: "إعادة تعيين كلمة المرور",
    descriptionAr: "تعيين كلمة مرور أولية جديدة.",
    sensitivity: "ELEVATED",
  },
  {
    code: "user.manage_roles",
    domain: "ACCESS",
    resource: "user",
    action: "manage_roles",
    labelAr: "إدارة أدوار المستخدم",
    descriptionAr: "إسناد الأدوار وإزالتها.",
    sensitivity: "CRITICAL",
  },
  {
    code: "user.manage_permissions",
    domain: "ACCESS",
    resource: "user",
    action: "manage_permissions",
    labelAr: "إدارة صلاحيات المستخدم المباشرة",
    descriptionAr: "منح أو رفض صلاحيات مباشرة للمستخدم.",
    sensitivity: "CRITICAL",
  },
  {
    code: "user.activity.view",
    domain: "ACCESS",
    resource: "user_activity",
    action: "view",
    labelAr: "عرض نشاط المستخدم",
    descriptionAr: "عرض سجل عمليات مستخدم محدد.",
    sensitivity: "ELEVATED",
  },
  {
    code: "user.sessions.view",
    domain: "ACCESS",
    resource: "user_session",
    action: "view",
    labelAr: "عرض جلسات المستخدم",
    descriptionAr: "عرض الجلسات النشطة والمنتهية.",
    sensitivity: "ELEVATED",
  },
  {
    code: "user.sessions.revoke",
    domain: "ACCESS",
    resource: "user_session",
    action: "revoke",
    labelAr: "إبطال جلسة مستخدم",
    descriptionAr: "إنهاء جلسة مستخدم محددة.",
    sensitivity: "CRITICAL",
  },
  {
    code: "role.view",
    domain: "ACCESS",
    resource: "role",
    action: "view",
    labelAr: "عرض الأدوار",
    descriptionAr: "عرض الأدوار وصلاحياتها ومستخدميها.",
    sensitivity: "NORMAL",
  },
  {
    code: "role.create",
    domain: "ACCESS",
    resource: "role",
    action: "create",
    labelAr: "إنشاء دور",
    descriptionAr: "إنشاء دور مخصص جديد.",
    sensitivity: "CRITICAL",
  },
  {
    code: "role.update",
    domain: "ACCESS",
    resource: "role",
    action: "update",
    labelAr: "تعديل الدور",
    descriptionAr: "تعديل اسم ووصف وحالة الدور.",
    sensitivity: "CRITICAL",
  },
  {
    code: "role.delete",
    domain: "ACCESS",
    resource: "role",
    action: "delete",
    labelAr: "حذف دور",
    descriptionAr: "حذف دور مخصص غير مستخدم.",
    sensitivity: "CRITICAL",
  },
  {
    code: "role.assign",
    domain: "ACCESS",
    resource: "role",
    action: "assign",
    labelAr: "إسناد الأدوار",
    descriptionAr: "إسناد دور إلى المستخدمين أو إزالته.",
    sensitivity: "CRITICAL",
  },
  {
    code: "role.manage_permissions",
    domain: "ACCESS",
    resource: "role_permission",
    action: "manage",
    labelAr: "إدارة صلاحيات الأدوار",
    descriptionAr: "تغيير الصلاحيات الموروثة من الدور.",
    sensitivity: "CRITICAL",
  },
  {
    code: "permission.view",
    domain: "ACCESS",
    resource: "permission",
    action: "view",
    labelAr: "عرض نموذج الصلاحيات",
    descriptionAr: "استعراض كتالوج ومصفوفة الصلاحيات.",
    sensitivity: "NORMAL",
  },
  {
    code: "permission.manage",
    domain: "ACCESS",
    resource: "permission",
    action: "manage",
    labelAr: "إدارة نموذج الصلاحيات",
    descriptionAr: "إدارة المنح المباشر وصلاحيات الأدوار.",
    sensitivity: "CRITICAL",
  },
] as const;
const LEGACY_ROLE_PERMISSION_MAP = {
  READER: [],
  DATA_ENTRY: [
    "dashboard.view",
    "reference.view",
    "source.view",
    "source.upload",
    "source.create_draft",
    "source.update",
    "legislation.view",
    "legislation.create",
    "legislation.update",
    "legislation.submit",
    "article.update",
    "structure.manage",
    "annex.manage",
    "amendment.view",
    "amendment.create",
  ],
  LEGAL_REVIEWER: [
    "dashboard.view",
    "reference.view",
    "source.view",
    "source.review",
    "source.update",
    "legislation.view",
    "legislation.approve",
    "legislation.submit",
    "relation.manage",
    "amendment.view",
    "amendment.review",
    "quality.view",
    "quality.manage",
  ],
  CONTENT_MANAGER: [
    "dashboard.view",
    "reference.view",
    "reference.manage",
    "source.view",
    "legislation.view",
    "legislation.update",
    "legislation.update_published_metadata",
    "legislation.publish",
    "legislation.archive",
    "structure.manage",
    "annex.manage",
    "relation.manage",
    "amendment.view",
    "amendment.publish",
    "quality.view",
    "quality.manage",
    "report.view",
    "report.manage",
    "audit.view",
    "search.synonym.view",
    "search.synonym.manage",
    "search.reindex",
    "settings.view",
    "settings.content.update",
  ],
  SYSTEM_ADMIN: [
    "dashboard.view",
    "reference.view",
    "source.view",
    "quality.view",
    "audit.view",
    "search.reindex",
    "settings.view",
    "settings.general.update",
    "settings.appearance.update",
    "settings.navigation.update",
    "settings.content.update",
    "settings.workflow.manage",
    "user.view",
    "user.create",
    "user.update",
    "user.disable",
    "user.reset_password",
    "user.manage_roles",
    "user.manage_permissions",
    "user.activity.view",
    "user.sessions.view",
    "user.sessions.revoke",
    "role.view",
    "role.create",
    "role.update",
    "role.delete",
    "role.assign",
    "role.manage_permissions",
    "permission.view",
    "permission.manage",
  ],
} as const;

export class GranularAccessControl1700000000010 implements MigrationInterface {
  name = "GranularAccessControl1700000000010";

  async up(q: QueryRunner): Promise<void> {
    await q.query(`CREATE TABLE permission_definitions (
      code VARCHAR(120) PRIMARY KEY,
      domain_code VARCHAR(60) NOT NULL,
      resource_code VARCHAR(80) NOT NULL,
      action_code VARCHAR(80) NOT NULL,
      label_ar VARCHAR(200) NOT NULL,
      description_ar VARCHAR(1000) NOT NULL,
      sensitivity ENUM('NORMAL','ELEVATED','CRITICAL') NOT NULL DEFAULT 'NORMAL',
      supported_scopes_json JSON NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
      KEY idx_permission_group (domain_code,resource_code,action_code),
      KEY idx_permission_sensitivity (sensitivity,is_active)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);

    await q.query(`CREATE TABLE role_permissions (
      role_id CHAR(36) NOT NULL,
      permission_code VARCHAR(120) NOT NULL,
      scope_code ENUM('ALL','OWN','ASSIGNED') NOT NULL DEFAULT 'ALL',
      granted_by CHAR(36) NULL,
      granted_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      PRIMARY KEY (role_id,permission_code),
      CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
      CONSTRAINT fk_role_permission_definition FOREIGN KEY (permission_code) REFERENCES permission_definitions(code),
      CONSTRAINT fk_role_permission_grantor FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE SET NULL,
      KEY idx_role_permission_code (permission_code,scope_code)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);

    await q.query(`CREATE TABLE user_permission_overrides (
      user_id CHAR(36) NOT NULL,
      permission_code VARCHAR(120) NOT NULL,
      effect ENUM('ALLOW','DENY') NOT NULL,
      scope_code ENUM('ALL','OWN','ASSIGNED') NOT NULL DEFAULT 'ALL',
      granted_by CHAR(36) NULL,
      reason VARCHAR(1000) NOT NULL,
      granted_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      PRIMARY KEY (user_id,permission_code),
      CONSTRAINT fk_user_permission_override_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      CONSTRAINT fk_user_permission_override_definition FOREIGN KEY (permission_code) REFERENCES permission_definitions(code),
      CONSTRAINT fk_user_permission_override_grantor FOREIGN KEY (granted_by) REFERENCES users(id) ON DELETE SET NULL,
      KEY idx_user_permission_override_code (permission_code,effect)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);

    await q.query(`ALTER TABLE roles
      ADD COLUMN description_ar VARCHAR(1000) NULL AFTER name_ar,
      ADD COLUMN is_system BOOLEAN NOT NULL DEFAULT TRUE AFTER permissions_json,
      ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE AFTER is_system,
      ADD COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)`);
    await q.query(`ALTER TABLE user_roles
      ADD COLUMN assigned_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      ADD COLUMN assigned_by CHAR(36) NULL,
      ADD CONSTRAINT fk_user_role_assigner FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE SET NULL`);

    for (const item of PERMISSION_CATALOG)
      await q.query(
        `INSERT INTO permission_definitions
        (code,domain_code,resource_code,action_code,label_ar,description_ar,sensitivity,supported_scopes_json)
        VALUES (?,?,?,?,?,?,?,?)`,
        [
          item.code,
          item.domain,
          item.resource,
          item.action,
          item.labelAr,
          item.descriptionAr,
          item.sensitivity,
          JSON.stringify(["ALL"]),
        ],
      );

    for (const [roleCode, permissions] of Object.entries(
      LEGACY_ROLE_PERMISSION_MAP,
    ))
      for (const permissionCode of permissions)
        await q.query(
          `INSERT INTO role_permissions (role_id,permission_code,scope_code)
          SELECT id,?,'ALL' FROM roles WHERE code=?`,
          [permissionCode, roleCode],
        );

    const descriptions: Record<string, string> = {
      READER: "الوصول العام وأدوات الحساب الشخصية دون دخول لوحة الإدارة.",
      DATA_ENTRY: "استيراد المصادر وإنشاء المسودات وتحرير النصوص القانونية.",
      LEGAL_REVIEWER: "مراجعة المصادر والتشريعات والتعديلات ومعالجة الجودة.",
      CONTENT_MANAGER: "إدارة المحتوى والنشر والقواميس والبلاغات.",
      SYSTEM_ADMIN: "إدارة المنصة والمستخدمين والأدوار والصلاحيات.",
    };
    for (const [code, description] of Object.entries(descriptions))
      await q.query("UPDATE roles SET description_ar=? WHERE code=?", [
        description,
        code,
      ]);
  }

  async down(q: QueryRunner): Promise<void> {
    await q.query(
      "ALTER TABLE user_roles DROP FOREIGN KEY fk_user_role_assigner,DROP COLUMN assigned_by,DROP COLUMN assigned_at",
    );
    await q.query(
      "ALTER TABLE roles DROP COLUMN updated_at,DROP COLUMN is_active,DROP COLUMN is_system,DROP COLUMN description_ar",
    );
    await q.query("DROP TABLE user_permission_overrides");
    await q.query("DROP TABLE role_permissions");
    await q.query("DROP TABLE permission_definitions");
  }
}
