import type { PermissionDefinition } from "./permission-catalog.js";

type DefinitionInput = readonly [
  code: string,
  domain: string,
  labelAr: string,
  descriptionAr: string,
  sensitivity?: PermissionDefinition["sensitivity"],
];

const definition = ([
  code,
  domain,
  labelAr,
  descriptionAr,
  sensitivity = "NORMAL",
]: DefinitionInput): PermissionDefinition => {
  const parts = code.split(".");
  return {
    code,
    domain,
    resource: parts.slice(0, -1).join("."),
    action: parts.at(-1)!,
    labelAr,
    descriptionAr,
    sensitivity,
  };
};

const definitions: DefinitionInput[] = [
  [
    "dashboard.view",
    "OVERVIEW",
    "عرض لوحة المؤشرات",
    "عرض مؤشرات الإدارة العامة.",
  ],
  [
    "legislation.view",
    "CONTENT",
    "عرض التشريعات الإدارية",
    "عرض التشريعات والمسودات في لوحة الإدارة.",
  ],
  [
    "legislation.create",
    "CONTENT",
    "إنشاء تشريع",
    "إنشاء مسودة تشريع جديدة.",
    "ELEVATED",
  ],
  [
    "legislation.update",
    "CONTENT",
    "تعديل مسودة تشريع",
    "تعديل بيانات تشريع في حالة قابلة للتحرير.",
    "ELEVATED",
  ],
  [
    "legislation.published_metadata.update",
    "CONTENT",
    "تصحيح بيانات تشريع منشور",
    "تصحيح البيانات الوصفية دون تغيير النص المنشور.",
    "ELEVATED",
  ],
  [
    "legislation.prepare",
    "CONTENT",
    "تجهيز الوارد كمسودة",
    "نقل التشريع الوارد إلى حالة المسودة.",
    "ELEVATED",
  ],
  [
    "legislation.submit",
    "CONTENT",
    "إرسال التشريع للمراجعة",
    "نقل المسودة إلى المراجعة.",
    "ELEVATED",
  ],
  [
    "legislation.return",
    "CONTENT",
    "إعادة التشريع للمسودة",
    "إعادة التشريع من المراجعة إلى المسودة.",
    "ELEVATED",
  ],
  [
    "legislation.approve",
    "CONTENT",
    "اعتماد التشريع",
    "اعتماد التشريع ليصبح جاهزًا للنشر.",
    "CRITICAL",
  ],
  [
    "legislation.publish",
    "CONTENT",
    "نشر التشريع",
    "نشر النسخة المعتمدة للعامة.",
    "CRITICAL",
  ],
  [
    "legislation.archive",
    "CONTENT",
    "أرشفة التشريع",
    "نقل التشريع المنشور أو حالته القانونية إلى الأرشيف.",
    "ELEVATED",
  ],
  [
    "article.update",
    "CONTENT",
    "تعديل المواد",
    "تعديل نص المادة وبياناتها وموقعها.",
    "ELEVATED",
  ],
  [
    "structure.create",
    "CONTENT",
    "إنشاء عقدة بنية",
    "إنشاء باب أو فصل أو قسم ضمن تشريع.",
    "ELEVATED",
  ],
  [
    "structure.update",
    "CONTENT",
    "تعديل بنية التشريع",
    "تعديل أو نقل أو ترتيب عقدة بنية.",
    "ELEVATED",
  ],
  [
    "annex.create",
    "CONTENT",
    "إنشاء ملحق",
    "إنشاء ملحق وربطه بمصدر.",
    "ELEVATED",
  ],
  [
    "annex.update",
    "CONTENT",
    "تعديل ملحق",
    "تعديل بيانات ملحق في حالة المسودة.",
    "ELEVATED",
  ],
  ["annex.publish", "CONTENT", "نشر ملحق", "إتاحة الملحق للعامة.", "CRITICAL"],
  [
    "annex.replace",
    "CONTENT",
    "استبدال ملحق",
    "وسم الملحق كمستبدل مع حفظ تاريخه.",
    "CRITICAL",
  ],
  [
    "annex.repeal",
    "CONTENT",
    "إلغاء ملحق قانونيًا",
    "إنهاء الأثر القانوني للملحق دون سحب تاريخه.",
    "CRITICAL",
  ],
  [
    "relation.create",
    "CONTENT",
    "إنشاء علاقة قانونية",
    "إنشاء علاقة بين تشريعين.",
    "ELEVATED",
  ],
  [
    "relation.update",
    "CONTENT",
    "تعديل علاقة قانونية",
    "تعديل بيانات علاقة قانونية.",
    "ELEVATED",
  ],
  [
    "relation.review",
    "CONTENT",
    "مراجعة علاقة قانونية",
    "اعتماد أو رفض علاقة قانونية.",
    "ELEVATED",
  ],
  [
    "reference.view",
    "CONTENT",
    "عرض القوائم المرجعية",
    "عرض الأنواع والجهات والموضوعات.",
  ],
  [
    "reference.create",
    "CONTENT",
    "إنشاء قيمة مرجعية",
    "إنشاء نوع أو جهة أو موضوع.",
    "ELEVATED",
  ],
  [
    "reference.update",
    "CONTENT",
    "تعديل قيمة مرجعية",
    "تعديل أو تفعيل قيمة مرجعية.",
    "ELEVATED",
  ],
  [
    "source.view",
    "SOURCES",
    "عرض المصادر",
    "عرض المصادر وملفاتها ونتائج الاستخراج.",
    "ELEVATED",
  ],
  ["source.upload", "SOURCES", "رفع مصدر", "رفع ملف مصدر جديد.", "ELEVATED"],
  [
    "source.review",
    "SOURCES",
    "مراجعة المصدر",
    "اعتماد النص المستخرج بعد مقارنته بالمصدر.",
    "ELEVATED",
  ],
  [
    "source.draft.create",
    "SOURCES",
    "إنشاء مسودة من مصدر",
    "تحويل المصدر المستخرج إلى مسودة تشريع.",
    "ELEVATED",
  ],
  [
    "source.update",
    "SOURCES",
    "تعديل بيانات المصدر",
    "تصحيح بيانات المصدر وحالة الاستخراج.",
    "ELEVATED",
  ],
  [
    "amendment.view",
    "AMENDMENTS",
    "عرض التعديلات",
    "عرض مسودات وعمليات التعديل.",
  ],
  [
    "amendment.create",
    "AMENDMENTS",
    "إنشاء تعديل",
    "إنشاء مسودة عملية تعديل.",
    "ELEVATED",
  ],
  [
    "amendment.review",
    "AMENDMENTS",
    "مراجعة تعديل",
    "اعتماد المراجعة القانونية للتعديل.",
    "CRITICAL",
  ],
  [
    "amendment.publish",
    "AMENDMENTS",
    "نشر تعديل",
    "تطبيق التعديل وإنشاء نسخة زمنية.",
    "CRITICAL",
  ],
  ["quality.view", "GOVERNANCE", "عرض مشكلات الجودة", "عرض نتائج فحوص الجودة."],
  [
    "quality.resolve",
    "GOVERNANCE",
    "معالجة مشكلة جودة",
    "حل مشكلة جودة أو تجاهلها.",
    "ELEVATED",
  ],
  [
    "report.view",
    "GOVERNANCE",
    "عرض بلاغات المحتوى",
    "عرض البلاغات المقدمة عن المحتوى.",
    "ELEVATED",
  ],
  [
    "report.update",
    "GOVERNANCE",
    "معالجة بلاغ محتوى",
    "فرز البلاغ أو حله أو رفضه.",
    "ELEVATED",
  ],
  [
    "audit.view",
    "GOVERNANCE",
    "عرض سجل التدقيق",
    "عرض سجل العمليات غير القابل للتعديل.",
    "ELEVATED",
  ],
  [
    "search.synonym.view",
    "SEARCH",
    "عرض قاموس البحث",
    "عرض مجموعات المرادفات.",
  ],
  [
    "search.synonym.create",
    "SEARCH",
    "إنشاء مرادف",
    "إضافة مرادف إلى مجموعة المسودة.",
    "ELEVATED",
  ],
  [
    "search.synonym.delete",
    "SEARCH",
    "حذف مرادف",
    "حذف مرادف من مجموعة المسودة.",
    "ELEVATED",
  ],
  [
    "search.synonym_set.activate",
    "SEARCH",
    "تفعيل مجموعة مرادفات",
    "تفعيل مجموعة مرادفات وأرشفة المجموعة السابقة.",
    "CRITICAL",
  ],
  [
    "search.index.rebuild",
    "SEARCH",
    "إعادة بناء فهرس البحث",
    "إعادة بناء فهرس البحث المشتق كاملًا.",
    "ELEVATED",
  ],
  [
    "settings.view",
    "SETTINGS",
    "عرض إعدادات المنصة",
    "عرض إعدادات المنصة الإدارية.",
  ],
  [
    "settings.general.update",
    "SETTINGS",
    "تحديث الإعدادات العامة",
    "تحديث الهوية العامة للمنصة.",
    "ELEVATED",
  ],
  [
    "settings.appearance.update",
    "SETTINGS",
    "تحديث المظهر",
    "تحديث الألوان والخلفية والخطوط.",
    "ELEVATED",
  ],
  [
    "settings.header.update",
    "SETTINGS",
    "تحديث الترويسة",
    "تحديث إعدادات الترويسة.",
    "ELEVATED",
  ],
  [
    "settings.footer.update",
    "SETTINGS",
    "تحديث التذييل",
    "تحديث إعدادات التذييل.",
    "ELEVATED",
  ],
  [
    "settings.legislation_page.update",
    "SETTINGS",
    "تحديث صفحة التشريع",
    "تحديث تبويبات وعرض صفحة التشريع.",
    "ELEVATED",
  ],
  [
    "navigation.create",
    "SETTINGS",
    "إنشاء عنصر تنقل",
    "إضافة رابط إلى قوائم التنقل.",
    "ELEVATED",
  ],
  [
    "navigation.update",
    "SETTINGS",
    "تعديل عنصر تنقل",
    "تعديل أو إخفاء أو ترتيب رابط تنقل.",
    "ELEVATED",
  ],
  [
    "public_page.update",
    "SETTINGS",
    "تعديل صفحة عامة",
    "تعديل محتوى صفحة عامة في حالة المسودة.",
    "ELEVATED",
  ],
  [
    "public_page.publish",
    "SETTINGS",
    "نشر صفحة عامة",
    "نشر صفحة المحتوى للعامة.",
    "CRITICAL",
  ],
  [
    "public_page.archive",
    "SETTINGS",
    "أرشفة صفحة عامة",
    "أرشفة صفحة محتوى عامة.",
    "ELEVATED",
  ],
  [
    "workflow_policy.view",
    "WORKFLOW",
    "عرض سياسات سير العمل",
    "عرض إعدادات الفصل بين الواجبات.",
  ],
  [
    "workflow_policy.update",
    "WORKFLOW",
    "تحديث سياسة سير العمل",
    "تحديث حالة أو تهيئة سياسة سير العمل.",
    "CRITICAL",
  ],
  [
    "workflow_policy.overrides.manage",
    "WORKFLOW",
    "إدارة استثناءات سير العمل",
    "إضافة أو إزالة مستخدمي استثناءات الفصل بين الواجبات.",
    "CRITICAL",
  ],
  [
    "user.view",
    "ACCESS",
    "عرض المستخدمين",
    "عرض الملف الأساسي للمستخدم.",
    "ELEVATED",
  ],
  [
    "user.create",
    "ACCESS",
    "إنشاء مستخدم",
    "إنشاء حساب ضمن الأدوار القابلة للإسناد.",
    "CRITICAL",
  ],
  [
    "user.update",
    "ACCESS",
    "تعديل المستخدم",
    "تعديل بيانات الملف الشخصي للمستخدم.",
    "ELEVATED",
  ],
  [
    "user.enable",
    "ACCESS",
    "تفعيل مستخدم",
    "إعادة تفعيل حساب مستخدم.",
    "CRITICAL",
  ],
  [
    "user.disable",
    "ACCESS",
    "تعطيل مستخدم",
    "تعطيل حساب مستخدم وإبطال جلساته.",
    "CRITICAL",
  ],
  [
    "user.reset_password",
    "ACCESS",
    "إعادة تعيين كلمة المرور",
    "إعادة تعيين كلمة مرور مستخدم وإبطال جلساته.",
    "CRITICAL",
  ],
  [
    "user.roles.manage",
    "ACCESS",
    "إدارة أدوار المستخدم",
    "إسناد الأدوار القابلة للإسناد أو إزالتها.",
    "CRITICAL",
  ],
  [
    "user.permissions.manage",
    "ACCESS",
    "إدارة صلاحيات المستخدم المباشرة",
    "إدارة ALLOW وDENY المباشرة ضمن سقف الفاعل.",
    "CRITICAL",
  ],
  [
    "user.activity.view",
    "ACCESS",
    "عرض نشاط المستخدم",
    "عرض سجل نشاط مستخدم.",
    "ELEVATED",
  ],
  [
    "user.sessions.view",
    "ACCESS",
    "عرض جلسات المستخدم",
    "عرض جلسات مستخدم وحالتها.",
    "ELEVATED",
  ],
  [
    "user.sessions.revoke",
    "ACCESS",
    "إبطال جلسة مستخدم",
    "إبطال جلسة مستخدم محددة.",
    "CRITICAL",
  ],
  [
    "role.view",
    "ACCESS",
    "عرض الأدوار",
    "عرض بيانات الدور الأساسية.",
    "ELEVATED",
  ],
  ["role.create", "ACCESS", "إنشاء دور", "إنشاء دور مخصص جديد.", "CRITICAL"],
  [
    "role.update",
    "ACCESS",
    "تعديل دور",
    "تعديل بيانات وحالة دور قابل للإدارة.",
    "CRITICAL",
  ],
  ["role.delete", "ACCESS", "حذف دور", "حذف دور مخصص غير مستخدم.", "CRITICAL"],
  [
    "role.permissions.manage",
    "ACCESS",
    "إدارة صلاحيات الدور",
    "تغيير منح دور قابل للإدارة ضمن سقف الفاعل.",
    "CRITICAL",
  ],
  [
    "permission.view",
    "ACCESS",
    "عرض كتالوج الصلاحيات",
    "عرض كتالوج الصلاحيات النظامي للقراءة فقط.",
    "ELEVATED",
  ],
];

export const CANONICAL_PERMISSION_CATALOG = definitions.map(definition);

if (CANONICAL_PERMISSION_CATALOG.length !== 75)
  throw new Error(
    `Canonical permission catalog must contain 75 entries; received ${CANONICAL_PERMISSION_CATALOG.length}.`,
  );

export const CANONICAL_PERMISSION_CODES = new Set(
  CANONICAL_PERMISSION_CATALOG.map((item) => item.code),
);

export const LEGACY_PERMISSION_ALIASES: Readonly<Record<string, string[]>> = {
  "legislation.update_published_metadata": [
    "legislation.published_metadata.update",
  ],
  "legislation.submit": ["legislation.submit"],
  "structure.manage": ["structure.create", "structure.update"],
  "annex.manage": ["annex.create", "annex.update"],
  "relation.manage": ["relation.create", "relation.update"],
  "reference.manage": ["reference.create", "reference.update"],
  "source.create_draft": ["source.draft.create"],
  "quality.manage": ["quality.resolve"],
  "report.manage": ["report.update"],
  "search.synonym.manage": [
    "search.synonym.create",
    "search.synonym.delete",
    "search.synonym_set.activate",
  ],
  "search.reindex": ["search.index.rebuild"],
  "settings.navigation.update": [
    "settings.header.update",
    "settings.footer.update",
    "navigation.create",
    "navigation.update",
  ],
  "settings.content.update": [
    "settings.legislation_page.update",
    "public_page.update",
    "public_page.publish",
    "public_page.archive",
  ],
  "settings.workflow.manage": [
    "workflow_policy.view",
    "workflow_policy.update",
  ],
  "user.disable": ["user.enable", "user.disable"],
  "user.manage_roles": ["user.roles.manage"],
  "role.assign": ["user.roles.manage"],
  "user.manage_permissions": ["user.permissions.manage"],
  "role.manage_permissions": ["role.permissions.manage"],
  "permission.manage": [],
};

const keep = (...codes: string[]) => codes;

export const CANONICAL_ROLE_PERMISSION_MAP: Readonly<Record<string, string[]>> =
  {
    READER: [],
    DATA_ENTRY: keep(
      "dashboard.view",
      "reference.view",
      "source.view",
      "source.upload",
      "source.draft.create",
      "source.update",
      "legislation.view",
      "legislation.create",
      "legislation.update",
      "legislation.prepare",
      "legislation.submit",
      "article.update",
      "structure.create",
      "structure.update",
      "annex.create",
      "annex.update",
      "amendment.view",
      "amendment.create",
    ),
    LEGAL_REVIEWER: keep(
      "dashboard.view",
      "reference.view",
      "source.view",
      "source.review",
      "source.update",
      "legislation.view",
      "legislation.approve",
      "legislation.return",
      "relation.create",
      "relation.update",
      "relation.review",
      "amendment.view",
      "amendment.review",
      "quality.view",
      "quality.resolve",
    ),
    CONTENT_MANAGER: keep(
      "dashboard.view",
      "reference.view",
      "reference.create",
      "reference.update",
      "source.view",
      "legislation.view",
      "legislation.update",
      "legislation.published_metadata.update",
      "legislation.publish",
      "legislation.archive",
      "structure.create",
      "structure.update",
      "annex.create",
      "annex.update",
      "annex.publish",
      "annex.replace",
      "annex.repeal",
      "relation.create",
      "relation.update",
      "amendment.view",
      "amendment.publish",
      "quality.view",
      "quality.resolve",
      "report.view",
      "report.update",
      "audit.view",
      "search.synonym.view",
      "search.synonym.create",
      "search.synonym.delete",
      "search.synonym_set.activate",
      "search.index.rebuild",
      "settings.view",
      "settings.legislation_page.update",
      "public_page.update",
      "public_page.publish",
      "public_page.archive",
    ),
    SYSTEM_ADMIN: keep(
      "dashboard.view",
      "reference.view",
      "source.view",
      "quality.view",
      "audit.view",
      "search.index.rebuild",
      "settings.view",
      "settings.general.update",
      "settings.appearance.update",
      "settings.header.update",
      "settings.footer.update",
      "settings.legislation_page.update",
      "navigation.create",
      "navigation.update",
      "public_page.update",
      "public_page.publish",
      "public_page.archive",
      "workflow_policy.view",
      "workflow_policy.update",
      "user.view",
      "user.create",
      "user.update",
      "user.enable",
      "user.disable",
      "user.reset_password",
      "user.roles.manage",
      "user.permissions.manage",
      "user.activity.view",
      "user.sessions.view",
      "user.sessions.revoke",
      "role.view",
      "role.create",
      "role.update",
      "role.delete",
      "role.permissions.manage",
      "permission.view",
    ),
    SUPER: CANONICAL_PERMISSION_CATALOG.map((item) => item.code),
  };

export const ROLE_AUTHORITY_LEVELS: Readonly<Record<string, number>> = {
  READER: 10,
  DATA_ENTRY: 100,
  LEGAL_REVIEWER: 200,
  CONTENT_MANAGER: 300,
  SYSTEM_ADMIN: 800,
  SUPER: 1000,
};
