import type { PermissionDefinition } from "./permission-catalog.js";
const entries: [string, string, string][] = [
  ["search.synonym_set.create", "SEARCH", "إنشاء مجموعة مرادفات"],
  ["search.synonym_set.delete", "SEARCH", "حذف مجموعة مرادفات"],
  ["search.synonym_set.disable", "SEARCH", "تعطيل مجموعة مرادفات"],
  ["search.synonym_set.enable", "SEARCH", "إعادة تفعيل مجموعة مرادفات"],
  ["legislation.delete", "CONTENT", "حذف التشريع"],
  ["legislation.disable", "CONTENT", "تعطيل التشريع"],
  ["legislation.enable", "CONTENT", "إعادة تفعيل التشريع"],
  ["article.delete", "CONTENT", "حذف المادة"],
  ["article.disable", "CONTENT", "تعطيل المادة"],
  ["article.enable", "CONTENT", "إعادة تفعيل المادة"],
  ["structure.delete", "CONTENT", "حذف العقدة البنيوية"],
  ["structure.disable", "CONTENT", "تعطيل العقدة البنيوية"],
  ["structure.enable", "CONTENT", "إعادة تفعيل العقدة البنيوية"],
  ["annex.delete", "CONTENT", "حذف الملحق"],
  ["annex.disable", "CONTENT", "تعطيل الملحق"],
  ["annex.enable", "CONTENT", "إعادة تفعيل الملحق"],
  ["relation.delete", "CONTENT", "حذف العلاقة"],
  ["relation.disable", "CONTENT", "تعطيل العلاقة"],
  ["relation.enable", "CONTENT", "إعادة تفعيل العلاقة"],
  ["source.delete", "SOURCES", "حذف المصدر"],
  ["source.disable", "SOURCES", "تعطيل المصدر"],
  ["source.enable", "SOURCES", "إعادة تفعيل المصدر"],
  ["amendment.delete", "AMENDMENTS", "حذف وثيقة التعديل أو عنصرها"],
  ["amendment.disable", "AMENDMENTS", "تعطيل وثيقة التعديل أو عنصرها"],
  ["amendment.enable", "AMENDMENTS", "إعادة تفعيل وثيقة التعديل أو عنصرها"],
  ["reference.delete", "CONTENT", "حذف سجل مرجعي"],
  ["reference.disable", "CONTENT", "تعطيل سجل مرجعي"],
  ["reference.enable", "CONTENT", "إعادة تفعيل سجل مرجعي"],
  ["navigation.delete", "SETTINGS", "حذف رابط التنقل"],
  ["navigation.disable", "SETTINGS", "تعطيل رابط التنقل"],
  ["navigation.enable", "SETTINGS", "إعادة تفعيل رابط التنقل"],
  ["public_page.delete", "SETTINGS", "حذف الصفحة العامة"],
  ["public_page.disable", "SETTINGS", "تعطيل الصفحة العامة"],
  ["public_page.enable", "SETTINGS", "إعادة تفعيل الصفحة العامة"],
  ["user.delete", "ACCESS", "حذف المستخدم"],
  ["search.synonym.disable", "SEARCH", "تعطيل المرادف"],
  ["search.synonym.enable", "SEARCH", "إعادة تفعيل المرادف"],
  ["article.create", "CONTENT", "إضافة مادة مسودة"],
  ["amendment.update", "AMENDMENTS", "تحرير وثيقة التعديل وعناصرها"],
  ["public_page.create", "SETTINGS", "إضافة صفحة عامة"],
  ["search.synonym.update", "SEARCH", "تعديل مرادف"],
];
export const CRUD_PERMISSION_CATALOG: PermissionDefinition[] = entries.map(
  ([code, domain, labelAr]) => ({
    code,
    domain,
    resource: code.slice(0, code.lastIndexOf(".")),
    action: code.slice(code.lastIndexOf(".") + 1),
    labelAr,
    descriptionAr: labelAr + " مع التحقق من الحالة والارتباطات وتسجيل التدقيق.",
    sensitivity: "ELEVATED",
  }),
);
