export type PermissionSensitivity = "NORMAL" | "ELEVATED" | "CRITICAL";

export interface PermissionDefinition {
  code: string;
  domain: string;
  resource: string;
  action: string;
  labelAr: string;
  descriptionAr: string;
  sensitivity: PermissionSensitivity;
}

const permission = (
  code: string,
  domain: string,
  resource: string,
  action: string,
  labelAr: string,
  descriptionAr: string,
  sensitivity: PermissionSensitivity = "NORMAL",
): PermissionDefinition => ({
  code,
  domain,
  resource,
  action,
  labelAr,
  descriptionAr,
  sensitivity,
});

export const LEGACY_PERMISSION_CATALOG: PermissionDefinition[] = [
  permission(
    "dashboard.view",
    "OVERVIEW",
    "dashboard",
    "view",
    "عرض لوحة المؤشرات",
    "عرض مؤشرات الإدارة العامة.",
  ),
  permission(
    "legislation.view",
    "CONTENT",
    "legislation",
    "view",
    "عرض التشريعات الإدارية",
    "عرض المسودات والتشريعات داخل لوحة الإدارة.",
  ),
  permission(
    "legislation.create",
    "CONTENT",
    "legislation",
    "create",
    "إنشاء تشريع",
    "إنشاء مسودة تشريع جديدة.",
  ),
  permission(
    "legislation.update",
    "CONTENT",
    "legislation",
    "update",
    "تعديل بيانات التشريع",
    "تعديل البيانات الوصفية والديباجة.",
  ),
  permission(
    "legislation.update_published_metadata",
    "CONTENT",
    "legislation",
    "update_published_metadata",
    "تصحيح بيانات تشريع منشور",
    "تصحيح البيانات الوصفية دون تغيير النص المنشور.",
    "ELEVATED",
  ),
  permission(
    "legislation.submit",
    "CONTENT",
    "legislation",
    "submit",
    "إرسال التشريع للمراجعة",
    "نقل المسودة إلى المراجعة.",
  ),
  permission(
    "legislation.approve",
    "CONTENT",
    "legislation",
    "approve",
    "اعتماد التشريع",
    "اعتماد التشريع ليصبح جاهزًا للنشر.",
    "ELEVATED",
  ),
  permission(
    "legislation.publish",
    "CONTENT",
    "legislation",
    "publish",
    "نشر التشريع",
    "نشر النسخة المعتمدة للعامة.",
    "CRITICAL",
  ),
  permission(
    "legislation.archive",
    "CONTENT",
    "legislation",
    "archive",
    "أرشفة التشريع",
    "نقل التشريع المنشور إلى الأرشيف.",
    "ELEVATED",
  ),
  permission(
    "article.update",
    "CONTENT",
    "article",
    "update",
    "تعديل المواد",
    "تعديل نص المادة وبياناتها.",
  ),
  permission(
    "structure.manage",
    "CONTENT",
    "structure",
    "manage",
    "إدارة بنية التشريع",
    "إنشاء وتعديل الأبواب والفصول والأقسام.",
  ),
  permission(
    "annex.manage",
    "CONTENT",
    "annex",
    "manage",
    "إدارة الملاحق والجداول",
    "إنشاء وتعديل اللوائح والملاحق والجداول.",
  ),
  permission(
    "relation.manage",
    "CONTENT",
    "relation",
    "manage",
    "إدارة العلاقات القانونية",
    "إنشاء وتدقيق علاقات التشريعات.",
  ),
  permission(
    "reference.view",
    "CONTENT",
    "reference",
    "view",
    "عرض القوائم المرجعية",
    "عرض الأنواع والجهات والموضوعات.",
  ),
  permission(
    "reference.manage",
    "CONTENT",
    "reference",
    "manage",
    "إدارة القوائم المرجعية",
    "إنشاء وتعديل الأنواع والجهات والموضوعات.",
    "ELEVATED",
  ),
  permission(
    "source.view",
    "SOURCES",
    "source",
    "view",
    "عرض المصادر",
    "عرض ملفات المصدر ونتائج الاستخراج.",
  ),
  permission(
    "source.upload",
    "SOURCES",
    "source",
    "upload",
    "رفع مصدر",
    "رفع ملف مصدر جديد.",
  ),
  permission(
    "source.review",
    "SOURCES",
    "source",
    "review",
    "مراجعة المصدر",
    "اعتماد النص المستخرج بعد مقارنته بالمصدر.",
    "ELEVATED",
  ),
  permission(
    "source.create_draft",
    "SOURCES",
    "source",
    "create_draft",
    "إنشاء مسودة من مصدر",
    "تحويل المصدر المستخرج إلى مسودة تشريع.",
  ),
  permission(
    "source.update",
    "SOURCES",
    "source",
    "update",
    "تعديل بيانات المصدر",
    "تصحيح بيانات المصدر وحالة الاستخراج.",
  ),
  permission(
    "amendment.view",
    "AMENDMENTS",
    "amendment",
    "view",
    "عرض التعديلات",
    "عرض مسودات وعمليات التعديل.",
  ),
  permission(
    "amendment.create",
    "AMENDMENTS",
    "amendment",
    "create",
    "إنشاء تعديل",
    "إنشاء مسودة عملية تعديل.",
  ),
  permission(
    "amendment.review",
    "AMENDMENTS",
    "amendment",
    "review",
    "مراجعة تعديل",
    "اعتماد المراجعة القانونية للتعديل.",
    "ELEVATED",
  ),
  permission(
    "amendment.publish",
    "AMENDMENTS",
    "amendment",
    "publish",
    "نشر تعديل",
    "تطبيق التعديل وإنشاء نسخة زمنية.",
    "CRITICAL",
  ),
  permission(
    "quality.view",
    "GOVERNANCE",
    "quality",
    "view",
    "عرض مشكلات الجودة",
    "عرض نتائج فحوص الجودة.",
  ),
  permission(
    "quality.manage",
    "GOVERNANCE",
    "quality",
    "manage",
    "معالجة مشكلات الجودة",
    "حل مشكلة جودة أو تجاهلها.",
  ),
  permission(
    "report.view",
    "GOVERNANCE",
    "report",
    "view",
    "عرض البلاغات",
    "عرض بلاغات المحتوى.",
  ),
  permission(
    "report.manage",
    "GOVERNANCE",
    "report",
    "manage",
    "معالجة البلاغات",
    "فرز البلاغات وحلها أو رفضها.",
  ),
  permission(
    "audit.view",
    "GOVERNANCE",
    "audit",
    "view",
    "عرض سجل التدقيق",
    "عرض العمليات الحساسة وتفاصيل تغيرها.",
    "ELEVATED",
  ),
  permission(
    "search.synonym.view",
    "SEARCH",
    "synonym",
    "view",
    "عرض قاموس البحث",
    "عرض نسخ المرادفات القانونية.",
  ),
  permission(
    "search.synonym.manage",
    "SEARCH",
    "synonym",
    "manage",
    "إدارة قاموس البحث",
    "إنشاء مرادفات ونشر نسخ القاموس.",
  ),
  permission(
    "search.reindex",
    "SEARCH",
    "index",
    "reindex",
    "إعادة بناء فهرس البحث",
    "إطلاق إعادة فهرسة كاملة.",
    "ELEVATED",
  ),
  permission(
    "settings.view",
    "SETTINGS",
    "settings",
    "view",
    "عرض إعدادات المنصة",
    "عرض الإعدادات والصفحات والتنقل.",
  ),
  permission(
    "settings.general.update",
    "SETTINGS",
    "settings",
    "general_update",
    "تعديل الإعدادات العامة",
    "تعديل اسم وهوية المنصة.",
    "ELEVATED",
  ),
  permission(
    "settings.appearance.update",
    "SETTINGS",
    "settings",
    "appearance_update",
    "تعديل الهوية والمظهر",
    "تعديل الألوان والخلفيات والطباعة.",
    "ELEVATED",
  ),
  permission(
    "settings.navigation.update",
    "SETTINGS",
    "navigation",
    "update",
    "إدارة روابط التنقل",
    "إنشاء وتعديل روابط الترويسة والتذييل.",
    "ELEVATED",
  ),
  permission(
    "settings.content.update",
    "SETTINGS",
    "public_page",
    "update",
    "إدارة الصفحات العامة",
    "تحرير ونشر الصفحات العامة.",
  ),
  permission(
    "settings.workflow.manage",
    "SETTINGS",
    "workflow_policy",
    "manage",
    "إدارة سياسات سير العمل",
    "تعطيل سياسات الفصل ومنح استثناءاتها.",
    "CRITICAL",
  ),
  permission(
    "user.view",
    "ACCESS",
    "user",
    "view",
    "عرض المستخدمين",
    "عرض الحسابات وحالتها.",
  ),
  permission(
    "user.create",
    "ACCESS",
    "user",
    "create",
    "إنشاء مستخدم",
    "إنشاء حساب إداري جديد.",
    "ELEVATED",
  ),
  permission(
    "user.update",
    "ACCESS",
    "user",
    "update",
    "تعديل المستخدم",
    "تعديل بيانات الحساب الأساسية.",
  ),
  permission(
    "user.disable",
    "ACCESS",
    "user",
    "disable",
    "تعطيل وتفعيل المستخدم",
    "تغيير حالة الحساب وإبطال جلساته.",
    "ELEVATED",
  ),
  permission(
    "user.reset_password",
    "ACCESS",
    "user",
    "reset_password",
    "إعادة تعيين كلمة المرور",
    "تعيين كلمة مرور أولية جديدة.",
    "ELEVATED",
  ),
  permission(
    "user.manage_roles",
    "ACCESS",
    "user",
    "manage_roles",
    "إدارة أدوار المستخدم",
    "إسناد الأدوار وإزالتها.",
    "CRITICAL",
  ),
  permission(
    "user.manage_permissions",
    "ACCESS",
    "user",
    "manage_permissions",
    "إدارة صلاحيات المستخدم المباشرة",
    "منح أو رفض صلاحيات مباشرة للمستخدم.",
    "CRITICAL",
  ),
  permission(
    "user.activity.view",
    "ACCESS",
    "user_activity",
    "view",
    "عرض نشاط المستخدم",
    "عرض سجل عمليات مستخدم محدد.",
    "ELEVATED",
  ),
  permission(
    "user.sessions.view",
    "ACCESS",
    "user_session",
    "view",
    "عرض جلسات المستخدم",
    "عرض الجلسات النشطة والمنتهية.",
    "ELEVATED",
  ),
  permission(
    "user.sessions.revoke",
    "ACCESS",
    "user_session",
    "revoke",
    "إبطال جلسة مستخدم",
    "إنهاء جلسة مستخدم محددة.",
    "CRITICAL",
  ),
  permission(
    "role.view",
    "ACCESS",
    "role",
    "view",
    "عرض الأدوار",
    "عرض الأدوار وصلاحياتها ومستخدميها.",
  ),
  permission(
    "role.create",
    "ACCESS",
    "role",
    "create",
    "إنشاء دور",
    "إنشاء دور مخصص جديد.",
    "CRITICAL",
  ),
  permission(
    "role.update",
    "ACCESS",
    "role",
    "update",
    "تعديل الدور",
    "تعديل اسم ووصف وحالة الدور.",
    "CRITICAL",
  ),
  permission(
    "role.delete",
    "ACCESS",
    "role",
    "delete",
    "حذف دور",
    "حذف دور مخصص غير مستخدم.",
    "CRITICAL",
  ),
  permission(
    "role.assign",
    "ACCESS",
    "role",
    "assign",
    "إسناد الأدوار",
    "إسناد دور إلى المستخدمين أو إزالته.",
    "CRITICAL",
  ),
  permission(
    "role.manage_permissions",
    "ACCESS",
    "role_permission",
    "manage",
    "إدارة صلاحيات الأدوار",
    "تغيير الصلاحيات الموروثة من الدور.",
    "CRITICAL",
  ),
  permission(
    "permission.view",
    "ACCESS",
    "permission",
    "view",
    "عرض نموذج الصلاحيات",
    "استعراض كتالوج ومصفوفة الصلاحيات.",
  ),
  permission(
    "permission.manage",
    "ACCESS",
    "permission",
    "manage",
    "إدارة نموذج الصلاحيات",
    "إدارة المنح المباشر وصلاحيات الأدوار.",
    "CRITICAL",
  ),
];

const codes = (...values: string[]) => values;

export const LEGACY_ROLE_PERMISSION_MAP: Record<string, string[]> = {
  READER: codes(),
  DATA_ENTRY: codes(
    "dashboard.view",
    "reference.view",
    "source.view",
    "source.upload",
    "source.create_draft",
    "source.update",
    "legislation.view",
    "legislation.create",
    "legislation.update",
    "legislation.submit",
    "article.update",
    "structure.manage",
    "annex.manage",
    "amendment.view",
    "amendment.create",
  ),
  LEGAL_REVIEWER: codes(
    "dashboard.view",
    "reference.view",
    "source.view",
    "source.review",
    "source.update",
    "legislation.view",
    "legislation.approve",
    "legislation.submit",
    "relation.manage",
    "amendment.view",
    "amendment.review",
    "quality.view",
    "quality.manage",
  ),
  CONTENT_MANAGER: codes(
    "dashboard.view",
    "reference.view",
    "reference.manage",
    "source.view",
    "legislation.view",
    "legislation.update",
    "legislation.update_published_metadata",
    "legislation.publish",
    "legislation.archive",
    "structure.manage",
    "annex.manage",
    "relation.manage",
    "amendment.view",
    "amendment.publish",
    "quality.view",
    "quality.manage",
    "report.view",
    "report.manage",
    "audit.view",
    "search.synonym.view",
    "search.synonym.manage",
    "search.reindex",
    "settings.view",
    "settings.content.update",
  ),
  SYSTEM_ADMIN: codes(
    "dashboard.view",
    "reference.view",
    "source.view",
    "quality.view",
    "audit.view",
    "search.reindex",
    "settings.view",
    "settings.general.update",
    "settings.appearance.update",
    "settings.navigation.update",
    "settings.content.update",
    "settings.workflow.manage",
    "user.view",
    "user.create",
    "user.update",
    "user.disable",
    "user.reset_password",
    "user.manage_roles",
    "user.manage_permissions",
    "user.activity.view",
    "user.sessions.view",
    "user.sessions.revoke",
    "role.view",
    "role.create",
    "role.update",
    "role.delete",
    "role.assign",
    "role.manage_permissions",
    "permission.view",
    "permission.manage",
  ),
};

export const PERMISSION_CATALOG = CANONICAL_PERMISSION_CATALOG;
export const ROLE_PERMISSION_MAP = CANONICAL_ROLE_PERMISSION_MAP;

export const permissionDefinition = (code: string) =>
  PERMISSION_CATALOG.find((item) => item.code === code);
import {
  CANONICAL_PERMISSION_CATALOG,
  CANONICAL_ROLE_PERMISSION_MAP,
} from "./canonical-permission-catalog.js";
