import { useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ErrorPanel, LoadingCards } from '../components/StatePanel';
import { useApi } from '../hooks/use-api';

interface ModificationData{years:Array<{year:number;count:number}>;amendments:Array<{id:string;titleAr:string;issueDate:string;effectiveFrom:string;year:number;sourceName:string;operations:Array<{id:string;operationType:string;articleLabel:string;citationText:string;previousText:string|null;newText:string|null}>}>}
const operations:Record<string,string>={ADD:'إضافة',REPLACE:'استبدال',DELETE:'حذف',REPEAL:'إلغاء',RENUMBER:'إعادة ترقيم',CORRECT:'تصحيح'};
export function ModificationsPage(){const{id}=useParams();const{data,error,loading,retry}=useApi<ModificationData>(id?`/legislations/${id}/modifications`:null);const[selected,setSelected]=useState<number|null>(null);const active=selected??data?.years[0]?.year??null;const shown=useMemo(()=>data?.amendments.filter((item)=>item.year===active)??[],[data,active]);return <div className="container page-shell"><Link className="back-dark" to={`/ar/legislations/${id}`}>← العودة إلى التشريع</Link><header className="page-title"><span className="eyebrow dark">سجل لا يفقد التاريخ</span><h1>تعديلات التشريع</h1><p>كل عملية مرتبطة بالمادة والنص قبلها وبعدها ومصدرها.</p></header>{loading?<LoadingCards/>:error?<ErrorPanel message={error.message} retry={retry}/>:<><div className="year-timeline" role="tablist" aria-label="سنوات التعديلات">{data?.years.map((item)=><button role="tab" aria-selected={active===item.year} key={item.year} onClick={()=>setSelected(item.year)}><strong>{item.year}</strong><span>{item.count} عمليات</span></button>)}</div><div className="amendment-list">{shown.map((amendment)=><article className="card amendment-card" key={amendment.id}><header><div><span className="tag">{amendment.effectiveFrom}</span><h2>{amendment.titleAr}</h2></div><small>المصدر: {amendment.sourceName}</small></header>{amendment.operations.map((op)=><details key={op.id}><summary><span>{operations[op.operationType]??op.operationType}</span> المادة {op.articleLabel}</summary><p>{op.citationText}</p><div className="comparison"><section><h3>النص السابق</h3><p>{op.previousText??'لا يوجد نص سابق لهذه العملية.'}</p></section><section><h3>النص الجديد</h3><p>{op.newText??'ألغيت العبارة المستهدفة.'}</p></section></div></details>)}</article>)}</div></>}</div>}

