import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { EmptyPanel, ErrorPanel, LoadingCards } from '../components/StatePanel';
import { useApi } from '../hooks/use-api';
interface Annex{ id:string;annexType:string;titleAr:string;status:string;versionNo:number;validFrom:string;fileId:string|null;fileName:string|null;pageCount:number|null;structuredTable:unknown; }
const labels:Record<string,string>={EXECUTIVE_REGULATION:'لائحة تنفيذية',TABLE:'جدول',FORM:'نموذج',ANNEX:'ملحق',MAP:'خريطة',TARIFF:'تعرفة',LIST:'قائمة',CORRECTION:'تصحيح'};
export function RegulationsPage(){const{id}=useParams();const{data,error,loading,retry}=useApi<Annex[]>(id?`/legislations/${id}/annexes`:null);const[open,setOpen]=useState<string|null>(null);return <div className="container page-shell"><Link className="back-dark" to={`/ar/legislations/${id}`}>← العودة إلى التشريع</Link><header className="page-title"><span className="eyebrow dark">إصدارات زمنية مستقلة</span><h1>اللوائح والجداول والملاحق</h1><p>ملفات المصدر منفصلة عن البيانات المنظمة ولا تحذف النسخة المستبدلة.</p></header>{loading?<LoadingCards/>:error?<ErrorPanel message={error.message} retry={retry}/>:!data?.length?<EmptyPanel/>:<div className="annex-list">{data.map((annex)=><article className="card annex-card" key={annex.id}><header><div><span className="tag">{labels[annex.annexType]??annex.annexType}</span><h2>{annex.titleAr}</h2><p>الإصدار {annex.versionNo} — نافذ من {annex.validFrom}</p></div><button className="button secondary" onClick={()=>setOpen(open===annex.id?null:annex.id)} aria-expanded={open===annex.id}>{open===annex.id?'إغلاق':'فتح'}</button></header>{open===annex.id&&<div className="annex-body">{annex.fileId?<div className="pdf-viewer"><div className="viewer-toolbar"><span>{annex.fileName} — {annex.pageCount} صفحة</span><a className="button" href={`/api/v1/annexes/${annex.id}/file`} download>تنزيل</a></div><iframe title={`عارض ${annex.titleAr}`} src={`/api/v1/annexes/${annex.id}/file#page=1&zoom=page-width`}/><p className="viewer-fallback">إن تعذر العرض، <a href={`/api/v1/annexes/${annex.id}/file`}>نزّل الملف مباشرة</a>.</p></div>:annex.structuredTable?<StructuredTable data={annex.structuredTable}/>:<EmptyPanel title="لا يوجد ملف لهذا الإصدار" body="بيانات الإصدار محفوظة، وسيضاف الملف بعد المراجعة."/>}</div>}</article>)}</div>}</div>}
function StructuredTable({data}:{data:unknown}){const value=typeof data==='string'?JSON.parse(data) as {columns:string[];rows:string[][]}:data as {columns:string[];rows:string[][]};return <div className="table-wrap"><table><thead><tr>{value.columns.map((column)=><th key={column}>{column}</th>)}</tr></thead><tbody>{value.rows.map((row,index)=><tr key={index}>{row.map((cell)=><td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div>}

