import { FormEvent } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useApi } from '../hooks/use-api';
import { EmptyPanel, ErrorPanel, LoadingCards } from '../components/StatePanel';

interface SearchResponse { query:string;items:Array<{entityType:string;entityId:string;legislationId:string;articleId:string|null;titleAr:string;legislationTitle:string;year:number;officialNumber:string;snippet:string;score:number;validFrom:string|null;validTo:string|null}>;meta:{total:number;page:number;pageCount:number};facets:{types:Array<{code:string;name:string;count:number}>}; }
export function SearchPage(){const [params,setParams]=useSearchParams();const q=params.get('q')??'';const at=params.get('at')??'';const path=q?`/search?${params.toString()}`:null;const {data,error,loading,retry}=useApi<SearchResponse>(path);
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const next=new URLSearchParams();const value=String(form.get('q')??'').trim();if(value)next.set('q',value);const date=String(form.get('at')??'');if(date)next.set('at',date);if(form.get('historical'))next.set('historical','true');setParams(next);};
  return <div className="container page-shell"><header className="page-title"><span className="eyebrow dark">داخل النصوص والنسخ</span><h1>البحث المتقدم</h1><p>استخدم علامات الاقتباس لعبارة حرفية، والشرطة قبل كلمة لاستبعادها.</p></header><form className="advanced-search" onSubmit={submit}><label>عبارة البحث<input name="q" defaultValue={q} placeholder={'مثال: "المال العام" الضريبة -الجمارك'}/></label><label>النص النافذ في تاريخ<input type="date" name="at" defaultValue={at}/></label><label className="checkbox"><input type="checkbox" name="historical" defaultChecked={params.get('historical')==='true'}/> تضمين النسخ التاريخية</label><button className="button">بحث</button></form>
    {q&&<div className="results-heading" aria-live="polite"><strong>{loading?'جار البحث…':`${data?.meta.total??0} نتيجة`}</strong>{data?.facets.types.map((f)=><span className="tag" key={f.code}>{f.name}: {f.count}</span>)}</div>}
    {loading?<LoadingCards/>:error?<ErrorPanel message={error.message} retry={retry}/>:q&&!data?.items.length?<EmptyPanel title="لا تطابقات"/>:<div className="search-results">{data?.items.map((item)=><article className="card search-result" key={`${item.entityType}-${item.entityId}`}><span className="tag">{item.entityType==='ARTICLE_VERSION'?'مادة':'تشريع'}</span><h2><Link to={item.articleId?`/ar/legislations/${item.legislationId}#article-${item.articleId}`:`/ar/legislations/${item.legislationId}`}>{item.titleAr}</Link></h2><p className="parent-title">{item.legislationTitle} — {item.officialNumber}/{item.year}</p><p>{item.snippet}</p>{item.validFrom&&<small>النسخة: {item.validFrom} — {item.validTo??'مستمرة'}</small>}</article>)}</div>}
  </div>}

